# big-data-europe/docker-hadoop
services:
  hadoop-namenode: 
    image: bde2020/hadoop-namenode:latest
    container_name: hadoop-namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - ./hadoop/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=hadoop
    env_file:
      - ./hadoop.env

  hadoop-datanode1:
    image: bde2020/hadoop-datanode:latest
    container_name: hadoop-datanode1
    restart: always
    ports:
      - 10000:9864
    volumes:
      - ./hadoop/datanode1:/hadoop/dfs/data 
    environment:
      - SERVICE_PRECONDITION:"hadoop-namenode:9870"
    env_file:
      - ./hadoop.env
  
  hadoop-datanode2:
    image: bde2020/hadoop-datanode:latest
    container_name: hadoop-datanode2
    restart: always
    ports:
      - 10001:9864
    volumes:
      - ./hadoop/datanode2:/hadoop/dfs/data 
    environment:
      - SERVICE_PRECONDITION:"hadoop-namenode:9870"
    env_file:
      - ./hadoop.env

  hadoop-datanode3:
    image: bde2020/hadoop-datanode:latest
    container_name: hadoop-datanode3
    restart: always
    ports:
      - 10002:9864
    volumes:
      - ./hadoop/datanode3:/hadoop/dfs/data 
    environment:
      - SERVICE_PRECONDITION:"hadoop-namenode:9870"
    env_file:
      - ./hadoop.env
    
  hadoop-resourcemanager:
    image: bde2020/hadoop-resourcemanager:latest
    container_name: hadoop-resourcemanager
    restart: always
    environment:
      - SERVICE_PRECONDITION:"hadoop-namenode:9000 hadoop-namenode:9870 hadoop-datanode1:9864 hadoop-datanode2:9864 hadoop-datanode3:9864"
    env_file:
      - ./hadoop.env
    
  hadoop-nodemanager:
    image: bde2020/hadoop-nodemanager:latest
    container_name: hadoop-nodemanager
    restart: always
    environment:
      - SERVICE_PRECONDITION:"hadoop-namenode:9000 hadoop-namenode:9870 hadoop-datanode1:9864 hadoop-datanode2:9864 hadoop-datanode3:9864 hadoop-resourcemanager:8088"
    env_file:
      - ./hadoop.env
    
  hadoop-historyserver:
    image: bde2020/hadoop-historyserver:latest
    container_name: hadoop-historyserver
    restart: always
    environment:
      - SERVICE_PRECONDITION:"hadoop-namenode:9000 hadoop-namenode:9870 hadoop-datanode1:9864 hadoop-datanode2:9864 hadoop-datanode3:9864 hadoop-resourcemanager:8088"
    volumes:
      - ./hadoop/historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env